// AUTO-GENERATED by src/tools/registry_gen.zig. Do not edit manually.

pub const Entry = struct {
    tool_id: usize,
    tool_name: []const u8,
    schema_fingerprint_hex: []const u8,
    requires_network: bool,
    native: bool,
};

pub const entries = [_]Entry{
    .{ .tool_id = 1, .tool_name = "echo", .schema_fingerprint_hex = "cf4319544dcaf7fc07c77d5dd7aebd045993a3453eae0c32f5e346322748a86f", .requires_network = false, .native = false },
    .{ .tool_id = 2, .tool_name = "fs_read", .schema_fingerprint_hex = "0a3392947637cefe827478bb7825034d7f3466437607299fbc6dfcffd919ae3e", .requires_network = false, .native = false },
    .{ .tool_id = 3, .tool_name = "fs_write", .schema_fingerprint_hex = "8494df3e9c30e1739063217c402b49ca3415dd53778525121678feb8823a0abd", .requires_network = false, .native = false },
    .{ .tool_id = 4, .tool_name = "http_fetch", .schema_fingerprint_hex = "a736479dfb3cd03f85e98467fe418e5b055c12329b5b02ce82b87282fc5fc9ef", .requires_network = true, .native = true },
    .{ .tool_id = 5, .tool_name = "shell_exec", .schema_fingerprint_hex = "f1ef60960ce7c2c57395a5f32b7e526a3aca2beb80fb1b336e6975729993f124", .requires_network = false, .native = true },
};
